"""
Part II: IHC H-DAB Channel Deconvolution, DAB Threshold Mask Generation, and Positive Region Extraction Pipeline
This script batch-processes RGBA IHC ROI images by performing H-DAB color deconvolution using Fiji/ImageJ, exporting nucleus and DAB channels. Alpha transparency withhold annotation of blank filling and ROI outlines. Binary DAB-positive masks were generated by thresholding, and these masks are applied back to the RGBA ROI images while preserving alpha transparency annotation. It supports batch processing by marker subfolders, both registered-and-aliggned (roiCrop) and registered-but-not-aligned (roiRaw) directory structures, customizable DAB thresholding, synchronized folder structures, automatic output creation, logging, and reporting of processed, missing, or failed files. Outputs include nucleus images, DAB channel images, binary masks, thresholded positive-region RGBA images, and processing logs. Dependencies: Python, numpy, opencv-python, pandas, Pillow, scipy, scikit-image, tifffile, pyimagej, scyjava, and Fiji/ImageJ. Author: Zonghan Gan"""
import os
import numpy as np
import imagej
import tifffile
import cv2
import pandas as pd
from PIL import Image
from scipy import stats
from skimage import measure
import shutil
from datetime import datetime
import imagej, scyjava
import pandas as pd
scyjava.config.add_option('-Xmx6g')
ij = imagej.init('sc.fiji:fiji', mode='interactive')
def deconvolve_and_save_channels_imagej(
    rgba_png_path: str,
    nu_output_dir: str,
    dab_output_dir: str,
    ij
):
    """
    H-DAB color deconvolution using Fiji (interactive mode).
    Saves nucleus and DAB directly into separate folders.
    Reattaches original alpha channel after Fiji export.
    """
    os.makedirs(nu_output_dir, exist_ok=True)
    os.makedirs(dab_output_dir, exist_ok=True)
    base = os.path.splitext(os.path.basename(rgba_png_path))[0]
    nu_path = os.path.join(nu_output_dir, base + "_Nu.png")
    dab_path = os.path.join(dab_output_dir, base + "_DAB.png")
    in_path = rgba_png_path.replace("\\", "/")
    nu_path_fiji = nu_path.replace("\\", "/")
    dab_path_fiji = dab_path.replace("\\", "/")
    macro = f"""
        open("{in_path}");
        run("Colour Deconvolution", "vectors=[H DAB]");
        titles = getList("image.titles");
        if (titles.length == 0) exit("No images found after deconvolution");
        nu_title = "";
        dab_title = "";
        for (i = 0; i < titles.length; i++) {{
            t = toLowerCase(titles[i]);
            if (indexOf(t, toLowerCase("{base}")) >= 0) {{
                if (indexOf(t, "colour_1") >= 0) nu_title = titles[i];
                if (indexOf(t, "colour_2") >= 0) dab_title = titles[i];
            }}
        }}
        if (nu_title == "" || dab_title == "") {{
            for (i = 0; i < titles.length; i++) {{
                t = toLowerCase(titles[i]);
                if (nu_title == "" && indexOf(t, "colour_1") >= 0) nu_title = titles[i];
                if (dab_title == "" && indexOf(t, "colour_2") >= 0) dab_title = titles[i];
            }}
        }}
        if (nu_title == "" || dab_title == "") {{
            print("=== DEBUG: open image titles ===");
            for (i = 0; i < titles.length; i++) print(titles[i]);
            exit("Colour Deconvolution outputs not found");
        }}
        selectWindow(nu_title);
        saveAs("PNG", "{nu_path_fiji}");
        selectWindow(dab_title);
        saveAs("PNG", "{dab_path_fiji}");
        close("*");
    """
    ij.py.run_macro(macro)
    # Restore alpha
    src = cv2.imread(rgba_png_path, cv2.IMREAD_UNCHANGED)
    if src is None or src.shape[2] != 4:
        raise RuntimeError(f"Input is not RGBA: {rgba_png_path}")
    alpha = src[:, :, 3]
    nu = cv2.imread(nu_path, cv2.IMREAD_GRAYSCALE)
    dab = cv2.imread(dab_path, cv2.IMREAD_GRAYSCALE)
    if nu is None or dab is None:
        raise RuntimeError("Fiji output missing")
    nu_rgba = np.dstack([nu, nu, nu, alpha])
    dab_rgba = np.dstack([dab, dab, dab, alpha])
    cv2.imwrite(nu_path, nu_rgba)
    cv2.imwrite(dab_path, dab_rgba)
        return nu_path, dab_path
def batch_deconvolve_folder_tree(input_root: str, output_root: str, ij):
    """
    Folder structure:
    input_root/
        tnf-a/*.png
        cd163/*.png
    output_root/
        Nucleus/tnf-a/*.png
        DAB/tnf-a/*.png
    """
    nucleus_root = os.path.join(output_root, "Nucleus")
    dab_root = os.path.join(output_root, "DAB")
    os.makedirs(nucleus_root, exist_ok=True)
    os.makedirs(dab_root, exist_ok=True)
    for target in sorted(os.listdir(input_root)):
        target_in = os.path.join(input_root, target)
        if not os.path.isdir(target_in):
            continue
        target_nu_out = os.path.join(nucleus_root, target)
        target_dab_out = os.path.join(dab_root, target)
        for fname in sorted(os.listdir(target_in)):
            if not fname.lower().endswith(".png"):
                continue
            in_path = os.path.join(target_in, fname)
            print(f"[RUN] {in_path}")
            deconvolve_and_save_channels_imagej(
                rgba_png_path=in_path,
                nu_output_dir=target_nu_out,
                dab_output_dir=target_dab_out,
                ij=ij
            )
        print("DONE.")
batch_deconvolve_folder_tree(
    input_root="H:\\workspace\\260211IHC\\roiCropAligned",
    output_root="H:\\workspace\\260211IHC\\test\\roiCropAligned",
    ij=ij
)
batch_deconvolve_folder_tree(
    input_root="H:\\workspace\\260211IHC\\roiRaw",
    output_root="H:\\workspace\\260211IHC\\test\\roiRaw",
    ij=ij
)
scyjava.shutdown_jvm()
"""
Convert a DAB image to a binary mask.
Rules:
- DAB in [low, high] -> white (255)
- Others -> black (0)
Output:
- Filename: replace 'DAB.png' with 'mask.png'
- Saved into output_folder
- Returns full output PNG path
"""
def dab_to_binary_mask(
    dab_png_path: str,
    output_folder: str,
    low: int = 0,
    high: int = 220
) -> str:
    """
    Convert a DAB image to a binary mask.
    Rules:
        - DAB in [low, high] -> white (255)
        - Others -> black (0)
    Output:
        - Filename: replace 'DAB.png' with 'mask.png'
        - Saved into output_folder
        - Returns full output PNG path
    """
    if not dab_png_path.lower().endswith(".png"):
        raise ValueError("Input must be a PNG file")
    os.makedirs(output_folder, exist_ok=True)
    # --- output filename ---
    base_name = os.path.basename(dab_png_path)
    #if "DAB.png" not in base_name:
    #    raise ValueError("Input filename must contain 'DAB.png'")
    out_name = base_name.replace(".png", "_mask.png")
    out_path = os.path.join(output_folder, out_name)
    # --- load DAB ---
    img = Image.open(dab_png_path).convert("L")
    arr = np.array(img)
    # --- binary mask ---
    mask = ((arr >= low) & (arr <= high)).astype(np.uint8) * 255
    Image.fromarray(mask, mode="L").save(out_path)
    return out_pathdef apply_mask_to_rgba_roi(
    rgba_png_path: str,
    mask_png_path: str,
    output_folder: str
) -> str:
    """
    Apply a binary mask to an RGBA ROI image.
    Mask rules:
        - mask == 255 -> keep original RGBA
        - mask == 0   -> set RGBA to (0,0,0,0)
    Output filename:
        xxx-mask.png -> xxx-mskTest.png
    """
    os.makedirs(output_folder, exist_ok=True)
    # --- load images ---
    rgba_img = Image.open(rgba_png_path).convert("RGBA")
    mask_img = Image.open(mask_png_path).convert("L")
    rgba = np.array(rgba_img)
    mask = np.array(mask_img)
    # --- apply mask ---
    keep = mask == 255
    out = np.zeros_like(rgba, dtype=np.uint8)
    out[keep] = rgba[keep]
    # --- output filename ---
    mask_name = os.path.basename(mask_png_path)
    if "mask.png" not in mask_name:
        raise ValueError("Mask filename must contain 'mask.png'")
    out_name = mask_name.replace("mask.png", "mskTest.png")
    out_path = os.path.join(output_folder, out_name)
    Image.fromarray(out, mode="RGBA").save(out_path)
return out_path
# -----------------------------
# Wrapper with logging
# -----------------------------
def batch_dab_masks_with_tree_copy(
    input_root: str,
    output_root: str,
    low: int = 0,
    high: int = 220,
    copy_non_png: bool = True,
    copy_png_inputs: bool = True,
) -> None:
    """
    Extended wrapper:
      - Mirror folder tree
      - Generate masks
      - Save execution log into output_root
    """
    start_time = datetime.now()
    if not os.path.isdir(input_root):
        raise ValueError(f"input_root does not exist: {input_root}")
    os.makedirs(output_root, exist_ok=True)
    # -----------------------------
    # 1) Save input parameter log
    # -----------------------------
    timestamp = start_time.strftime("%Y%m%d_%H%M%S")
    log_path = os.path.join(output_root, f"{timestamp}_mask_pipeline_log.txt")
    with open(log_path, "w", encoding="utf-8") as log:
        log.write("=" * 60 + "\n")
        log.write("DAB MASK BATCH PIPELINE LOG\n")
        log.write("=" * 60 + "\n\n")
        log.write(f"Start Time: {start_time}\n\n")
        log.write("INPUT PARAMETERS\n")
        log.write(f"input_root        : {input_root}\n")
        log.write(f"output_root       : {output_root}\n")
        log.write(f"low               : {low}\n")
        log.write(f"high              : {high}\n")
        log.write(f"copy_non_png      : {copy_non_png}\n")
        log.write(f"copy_png_inputs   : {copy_png_inputs}\n")
        log.write("\n")
    # -----------------------------
    # 2) Mirror directory tree
    # -----------------------------
    for root, dirs, files in os.walk(input_root):
        rel_dir = os.path.relpath(root, input_root)
        out_dir = output_root if rel_dir == "." else os.path.join(output_root, rel_dir)
        os.makedirs(out_dir, exist_ok=True)
        if copy_non_png or copy_png_inputs:
            for fn in files:
                src = os.path.join(root, fn)
                dst = os.path.join(out_dir, fn)
                is_png = fn.lower().endswith(".png")
                if (is_png and copy_png_inputs) or ((not is_png) and copy_non_png):
                    shutil.copy2(src, dst)
    # -----------------------------
    # 3) Process PNG masks
    # -----------------------------
    processed = 0
    skipped = 0
    failed = 0
    for root, _, files in os.walk(input_root):
        rel_dir = os.path.relpath(root, input_root)
        out_dir = output_root if rel_dir == "." else os.path.join(output_root, rel_dir)
        for fn in files:
            if not fn.lower().endswith(".png"):
                continue
            #if "DAB.png" not in fn:
            #    skipped += 1
            #    continue
            src_png = os.path.join(root, fn)
            try:
                tmp_mask_path = dab_to_binary_mask(
                    dab_png_path=src_png,
                    output_folder=out_dir,
                    low=low,
                    high=high,
                )
                # rename to *_mask.png
                #final_mask_path = os.path.splitext(tmp_mask_path)[0] 
                #+ "_mask.png"
                #if os.path.exists(final_mask_path):
                #    os.remove(final_mask_path)
                #os.replace(tmp_mask_path, final_mask_path)
                processed += 1
                print(f"[OK] {src_png}")
            except Exception as e:
                failed += 1
                print(f"[FAIL] {src_png} :: {e}")
    end_time = datetime.now()
    # -----------------------------
    # 4) Append summary to log
    # -----------------------------
    with open(log_path, "a", encoding="utf-8") as log:
        log.write("PROCESS SUMMARY\n")
        log.write(f"Processed : {processed}\n")
        log.write(f"Skipped   : {skipped}\n")
        log.write(f"Failed    : {failed}\n")
        log.write(f"\nEnd Time  : {end_time}\n")
        log.write(f"Duration  : {end_time - start_time}\n")
    print("\nDONE.")
    print(f"Log saved at: {log_path}")
return
batch_dab_masks_with_tree_copy(
        input_root=r"H:\workspace\260211IHC\test\roiRaw\H-DAB",
        output_root=r"H:\workspace\260211IHC\mask\roiRaw\H-DAB",
        low=0,
        high=220,
        copy_non_png=False,
        copy_png_inputs=False,
)
